### ISSUE TITLE
Status for most recent version of libolm

### ISSUE THREAD

**Issue by digitalplaywright** [Dhole/go-olm#2]
The README says these bindings are WIP, are there still plans to finish these bindings? Would you recommend people that are wanting to use libolm in go to start with go-olm?

**Comment by Dhole** [comment]
I have no plans to continue working on this repository.  The current state of `go-olm` is that the bindings where working in 2018 and if I recall correctly, I managed to successfully encrypt and decrypt matrix messages by then.  I don't know if or how the libolm library has evolved, and I don't remember if by 2018 there were some bindings missing.  So I wouldn't recommend using this expecting it to work.  Maybe it works, maybe things have changed.

If you'd like to use libolm from go, I would recommend either finding a more up to date go library, or making a fork of this one and test it with the current libolm, and update it if necessary.

**Comment by digitalplaywright** [comment]
Thank you for the quick answer! I will look into my options.
